baseURL = "https://alexhe.io"
languageCode = "en-us"
title = "Home ğŸ "
theme = "etch"

pygmentsUseClasses = true  # use class names instead of directly inserting color codes
pygmentsCodeFences = true  # enable GitHub style code snippets

[params]
  copyright = "Copyright Â© 2020 Alex He"
  description = "Personal website for Alex He"
  highlight = true
  dark = "auto"

[permalinks]
  posts = "/:title/"